
find_program(CCACHE_EXECUTABLE ccache)
set(chromium_build_dir "${CHROMIUM_SOURCE_TREE}/out/${CHROMIUM_PROFILE}")
cmake_host_system_information(RESULT core_count QUERY NUMBER_OF_PHYSICAL_CORES)
if(core_count GREATER 1)
  set(parallel_jobs ${core_count} CACHE STRING "The number of parallel jobs chromium build commands should use.")
else()
  set(parallel_jobs 1 CACHE STRING "The number of parallel jobs chromium build commands should use.")
endif()
set(gnargs " enable_ipfs=true ")
if(CCACHE_EXECUTABLE)
  set(gnargs " ${gnargs} cc_wrapper=\"${CCACHE_EXECUTABLE}\" ")
endif()
if(CMAKE_BUILD_TYPE STREQUAL Release)
  set(gnargs " ${gnargs} is_debug=false dcheck_always_on=false is_component_build=false ")
elseif(CMAKE_BUILD_TYPE STREQUAL Debug)
  set(gnargs " ${gnargs} is_debug=true  dcheck_always_on=true ")
  message(STATUS "Will build Chromium also in debug mode. Note, this has performance implications.")
else()
  message(FATAL_ERROR "Please choose either Debug or Release for CMAKE_BUILD_TYPE (was '${CMAKE_BUILD_TYPE}').")
endif()
if("${CMAKE_SYSTEM_NAME}" STREQUAL "Darwin")
  set(gnargs " ${gnargs} mac_deployment_target=\"13.0\" treat_warnings_as_errors=false ")
endif()
set(GN_ARGS "${gnargs}" CACHE STRING "Args to gn gen")
