include("${CMAKE_CURRENT_LIST_DIR}/depot_tools.cmake")
find_program(CCACHE_EXECUTABLE ccache)
set(chromium_build_dir "${CHROMIUM_SOURCE_TREE}/out/${CHROMIUM_PROFILE}")
cmake_host_system_information(RESULT core_count QUERY NUMBER_OF_PHYSICAL_CORES)
if(core_count GREATER 1)
  set(parallel_jobs ${core_count} CACHE STRING "The number of parallel jobs chromium build commands should use.")
else()
  set(parallel_jobs 1 CACHE STRING "The number of parallel jobs chromium build commands should use.")
endif()
if(Python3_EXECUTABLE)
  if(CCACHE_EXECUTABLE)
    set(gnargs " cc_wrapper=\"${CCACHE_EXECUTABLE}\" ")
  endif()
  if(CMAKE_BUILD_TYPE STREQUAL Release)
    set(gnargs " ${gnargs} is_debug=false dcheck_always_on=false ")
  elseif(CMAKE_BUILD_TYPE STREQUAL Debug)
    message(STATUS "Will build Chromium also in debug mode. Note, this has performance implications.")
  else()
    message(FATAL_ERROR "Please choose either Debug or Release for CMAKE_BUILD_TYPE (was '${CMAKE_BUILD_TYPE}').")
  endif()
endif()
set(GN_ARGS "${gnargs}" CACHE STRING "Args to gn gen")
