set(SETUP_CMAKE_INCLUDED 1)

set(protobuf_version "5.29.3")
if(USE_DOXYGEN)
    find_program(DOXYGEN_BIN doxygen)
    if (NOT DOXYGEN_BIN)
        set(doxygen_dep "doxygen/1.9.4")
    endif()
else()
    set(doxygen_dep "")
endif()

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR};${CMAKE_CURRENT_BINARY_DIR};${CMAKE_MODULE_PATH})
list(APPEND CMAKE_PREFIX_PATH "${CMAKE_CURRENT_BINARY_DIR}")
include(${CMAKE_CXX_COMPILER_ID})
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

include(conan_install)

find_package(Git QUIET)
if(USE_CLANG_TIDY)
  find_program(CLANG_TIDY_EXE NAMES "clang-tidy")
  if(NOT CLANG_TIDY_EXE)
      message(WARNING "clang-tidy not found")
  endif()
endif()
