name: Chromium in-tree browser build
on:
  pull_request:
    paths:
      - CMakeLists.txt
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "macOS Latest Clang",
              os: macos-latest,
              artifact: "macos_clang.7z",
              build_type: "Release",
              cc: "clang",
              cxx: "clang++",
              archiver: "7za a",
              generators: "Ninja"
            }
    steps:
      - uses: actions/checkout@v2
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          pwd
          git status
          which python3 
          python3 --version
      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip cmake ninja
          ninja --version
          cmake --version
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -G "${{ matrix.config.generators }}" \
            -S . \
            -B build \
            -D DOWNLOAD_CHROMIUM=ON \
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} chrome_browser
      - name: Package
        if: startsWith(matrix.config.build_type, 'Release')
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} package
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Static Library
#          path: build/library/*ipfs_client.* # libipfs_client.a or ipfs_client.lib
