name: Chromium in-tree browser build phase 2
on:
  workflow_run:
    workflows: ["Chromium in-tree browser build phase 1"]
    type:
      - complete
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "macOS Latest Clang",
              os: macos-latest,
              artifact: "macos_clang.7z",
              build_type: "Release",
              cc: "clang",
              cxx: "clang++",
              archiver: "7za a",
              generators: "Ninja"
            }
    steps:        
      - uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          pwd
          git status
          which python3 
          python3 --version
      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip cmake ninja
          ninja --version
          cmake --version
          which pip3
          pip3 --version
          pip3 install httplib2
      - name: Download
        uses: actions/download-artifact@v3
          with:
            name: wholebuildtree
      - name: Untar
        shell: bash
        run: tar -x -z -f wholebuildtree.tar.gz
      - name: Component build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target in_tree_build
      - name: Browser build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target chrome_browser
      - name: Package
        if: startsWith(matrix.config.build_type, 'Release')
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target package_browser
      - name: Upload
        if: startsWith(matrix.config.build_type, 'Release') && startsWith(matrix.config.os, 'macos')
        uses: actions/upload-artifact@v3
          with:
            name: chromiumbuildtree
            path: build/chromium/out/Release/*.dmg
            retention-days: 2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          export_default_credentials: true
      - name: Check gcloud CLI
        run: gcloud info
      - name: UploadGCloud
        if: startsWith(matrix.config.build_type, 'Release')
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target upload_browser
