name: Tour de IPFS
on:
  push:
  workflow_call:
jobs:
  tour:
    name: Build clitester and exercize various ipfs_client features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ipfs_chromium
        uses: actions/checkout@v4
        with:
          path: 'ipfs_chromium'
      - name: Run committed script
        run: ./ipfs_chromium/.github/tour.sh
          
