name: Unit Testing
on:
  push:
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    name: Run Tests & Publish Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'ipfs_chromium'
      - name: Run versioned script
        shell: bash
        run: ./ipfs_chromium/.github/ut.sh
      - name: Upload coverage reports to Codecov.com
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          files: build/library/cov.info
